// <auto-generated />
using System;
using Api.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(PaylocityContext))]
    [Migration("20231029213902_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Api.Models.Dependent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Relationship")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Dependents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2020, 5, 8, 16, 1, 7, 891, DateTimeKind.Local).AddTicks(4630),
                            EmployeeId = 1,
                            FirstName = "Jerel",
                            LastName = "Auer",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1994, 3, 3, 22, 45, 54, 784, DateTimeKind.Local).AddTicks(8274),
                            EmployeeId = 1,
                            FirstName = "Ryder",
                            LastName = "Treutel",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2014, 2, 13, 2, 13, 57, 207, DateTimeKind.Local).AddTicks(824),
                            EmployeeId = 1,
                            FirstName = "Elinor",
                            LastName = "Hills",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2013, 12, 16, 7, 54, 0, 222, DateTimeKind.Local).AddTicks(9575),
                            EmployeeId = 1,
                            FirstName = "Orlo",
                            LastName = "Murray",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2011, 5, 5, 23, 26, 20, 207, DateTimeKind.Local).AddTicks(3133),
                            EmployeeId = 3,
                            FirstName = "Bret",
                            LastName = "Hansen",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2020, 8, 18, 21, 49, 41, 758, DateTimeKind.Local).AddTicks(4990),
                            EmployeeId = 3,
                            FirstName = "Chelsey",
                            LastName = "Swaniawski",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2016, 3, 30, 12, 0, 44, 182, DateTimeKind.Local).AddTicks(4721),
                            EmployeeId = 3,
                            FirstName = "Maverick",
                            LastName = "Sporer",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2009, 6, 19, 6, 58, 37, 619, DateTimeKind.Local).AddTicks(7139),
                            EmployeeId = 3,
                            FirstName = "Audra",
                            LastName = "Trantow",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2012, 7, 23, 1, 12, 57, 840, DateTimeKind.Local).AddTicks(820),
                            EmployeeId = 4,
                            FirstName = "Lauretta",
                            LastName = "Mosciski",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2021, 5, 14, 22, 8, 41, 108, DateTimeKind.Local).AddTicks(9504),
                            EmployeeId = 4,
                            FirstName = "Lucious",
                            LastName = "Miller",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(2015, 3, 31, 2, 38, 16, 331, DateTimeKind.Local).AddTicks(6448),
                            EmployeeId = 5,
                            FirstName = "Martina",
                            LastName = "Berge",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(2001, 12, 14, 12, 15, 3, 383, DateTimeKind.Local).AddTicks(5780),
                            EmployeeId = 5,
                            FirstName = "Lillian",
                            LastName = "Dibbert",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1991, 4, 30, 2, 37, 14, 958, DateTimeKind.Local).AddTicks(7183),
                            EmployeeId = 6,
                            FirstName = "Carleton",
                            LastName = "Gorczany",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1999, 5, 8, 19, 12, 33, 231, DateTimeKind.Local).AddTicks(7500),
                            EmployeeId = 6,
                            FirstName = "Jovan",
                            LastName = "Bailey",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(2003, 6, 28, 7, 12, 46, 638, DateTimeKind.Local).AddTicks(6490),
                            EmployeeId = 7,
                            FirstName = "Daphnee",
                            LastName = "Zemlak",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(2021, 6, 25, 8, 51, 13, 189, DateTimeKind.Local).AddTicks(4649),
                            EmployeeId = 7,
                            FirstName = "Lucious",
                            LastName = "Ward",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(2021, 11, 18, 13, 55, 1, 334, DateTimeKind.Local).AddTicks(8369),
                            EmployeeId = 7,
                            FirstName = "Jeanette",
                            LastName = "McKenzie",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(2013, 11, 25, 12, 43, 5, 620, DateTimeKind.Local).AddTicks(4829),
                            EmployeeId = 7,
                            FirstName = "Eulah",
                            LastName = "Gleichner",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(2022, 8, 10, 1, 54, 39, 905, DateTimeKind.Local).AddTicks(123),
                            EmployeeId = 8,
                            FirstName = "Boris",
                            LastName = "Pfannerstill",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(2000, 5, 30, 14, 53, 46, 740, DateTimeKind.Local).AddTicks(5673),
                            EmployeeId = 8,
                            FirstName = "Carley",
                            LastName = "Langosh",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(2019, 3, 26, 13, 0, 20, 699, DateTimeKind.Local).AddTicks(5749),
                            EmployeeId = 8,
                            FirstName = "Catherine",
                            LastName = "Swaniawski",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(2019, 3, 21, 0, 23, 3, 247, DateTimeKind.Local).AddTicks(9156),
                            EmployeeId = 9,
                            FirstName = "Yolanda",
                            LastName = "Corwin",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(1996, 7, 13, 16, 22, 17, 54, DateTimeKind.Local).AddTicks(4079),
                            EmployeeId = 9,
                            FirstName = "Talon",
                            LastName = "Wunsch",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(2017, 12, 2, 23, 18, 23, 222, DateTimeKind.Local).AddTicks(9238),
                            EmployeeId = 9,
                            FirstName = "Emanuel",
                            LastName = "Mann",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(2021, 11, 28, 2, 30, 22, 907, DateTimeKind.Local).AddTicks(4454),
                            EmployeeId = 10,
                            FirstName = "Winston",
                            LastName = "Berge",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 26,
                            DateOfBirth = new DateTime(2000, 9, 5, 6, 17, 28, 630, DateTimeKind.Local).AddTicks(1864),
                            EmployeeId = 11,
                            FirstName = "Creola",
                            LastName = "Pfannerstill",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 27,
                            DateOfBirth = new DateTime(2002, 11, 11, 16, 34, 25, 958, DateTimeKind.Local).AddTicks(1750),
                            EmployeeId = 11,
                            FirstName = "Bill",
                            LastName = "King",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 28,
                            DateOfBirth = new DateTime(2018, 7, 3, 10, 46, 52, 15, DateTimeKind.Local).AddTicks(1883),
                            EmployeeId = 11,
                            FirstName = "Ilene",
                            LastName = "Runte",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 29,
                            DateOfBirth = new DateTime(2015, 12, 12, 20, 59, 21, 440, DateTimeKind.Local).AddTicks(7674),
                            EmployeeId = 11,
                            FirstName = "Bette",
                            LastName = "Klein",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 30,
                            DateOfBirth = new DateTime(2003, 9, 23, 16, 49, 59, 802, DateTimeKind.Local).AddTicks(3605),
                            EmployeeId = 12,
                            FirstName = "Hollis",
                            LastName = "Bailey",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 31,
                            DateOfBirth = new DateTime(2020, 2, 29, 23, 11, 56, 262, DateTimeKind.Local).AddTicks(2707),
                            EmployeeId = 12,
                            FirstName = "Ewell",
                            LastName = "Tremblay",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 32,
                            DateOfBirth = new DateTime(2017, 1, 11, 4, 25, 11, 611, DateTimeKind.Local).AddTicks(9243),
                            EmployeeId = 13,
                            FirstName = "Virginie",
                            LastName = "Sanford",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 33,
                            DateOfBirth = new DateTime(1999, 6, 6, 20, 10, 13, 643, DateTimeKind.Local).AddTicks(2359),
                            EmployeeId = 14,
                            FirstName = "Dudley",
                            LastName = "Weber",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 34,
                            DateOfBirth = new DateTime(2016, 11, 26, 16, 53, 7, 797, DateTimeKind.Local).AddTicks(7320),
                            EmployeeId = 14,
                            FirstName = "Finn",
                            LastName = "Hodkiewicz",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 35,
                            DateOfBirth = new DateTime(2005, 5, 16, 10, 29, 37, 587, DateTimeKind.Local).AddTicks(677),
                            EmployeeId = 15,
                            FirstName = "Daron",
                            LastName = "Cassin",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 36,
                            DateOfBirth = new DateTime(2015, 3, 25, 9, 49, 56, 781, DateTimeKind.Local).AddTicks(5778),
                            EmployeeId = 16,
                            FirstName = "Eusebio",
                            LastName = "Kozey",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 37,
                            DateOfBirth = new DateTime(2020, 1, 31, 18, 37, 41, 465, DateTimeKind.Local).AddTicks(6352),
                            EmployeeId = 17,
                            FirstName = "Hellen",
                            LastName = "Bahringer",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 38,
                            DateOfBirth = new DateTime(1999, 11, 11, 10, 23, 44, 987, DateTimeKind.Local).AddTicks(2640),
                            EmployeeId = 17,
                            FirstName = "Audreanne",
                            LastName = "Leuschke",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 39,
                            DateOfBirth = new DateTime(2017, 1, 22, 11, 29, 29, 561, DateTimeKind.Local).AddTicks(3575),
                            EmployeeId = 17,
                            FirstName = "Emmitt",
                            LastName = "Schuppe",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 40,
                            DateOfBirth = new DateTime(2004, 4, 2, 8, 28, 54, 112, DateTimeKind.Local).AddTicks(3470),
                            EmployeeId = 19,
                            FirstName = "Mikel",
                            LastName = "Lueilwitz",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 41,
                            DateOfBirth = new DateTime(2017, 6, 13, 0, 0, 18, 725, DateTimeKind.Local).AddTicks(7830),
                            EmployeeId = 19,
                            FirstName = "Diamond",
                            LastName = "Luettgen",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 42,
                            DateOfBirth = new DateTime(1997, 6, 26, 18, 28, 50, 584, DateTimeKind.Local).AddTicks(3985),
                            EmployeeId = 19,
                            FirstName = "Candace",
                            LastName = "Becker",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 43,
                            DateOfBirth = new DateTime(2000, 1, 2, 4, 54, 56, 480, DateTimeKind.Local).AddTicks(7253),
                            EmployeeId = 20,
                            FirstName = "Ari",
                            LastName = "Bartell",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 44,
                            DateOfBirth = new DateTime(2019, 7, 5, 11, 39, 56, 758, DateTimeKind.Local).AddTicks(2000),
                            EmployeeId = 20,
                            FirstName = "Rhoda",
                            LastName = "Davis",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 45,
                            DateOfBirth = new DateTime(2008, 11, 14, 4, 37, 35, 921, DateTimeKind.Local).AddTicks(8489),
                            EmployeeId = 20,
                            FirstName = "Charlie",
                            LastName = "Purdy",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 46,
                            DateOfBirth = new DateTime(2014, 10, 17, 16, 56, 19, 521, DateTimeKind.Local).AddTicks(9237),
                            EmployeeId = 21,
                            FirstName = "Jimmy",
                            LastName = "Streich",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 47,
                            DateOfBirth = new DateTime(2004, 9, 6, 5, 59, 44, 691, DateTimeKind.Local).AddTicks(1059),
                            EmployeeId = 21,
                            FirstName = "Lesly",
                            LastName = "Schimmel",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 48,
                            DateOfBirth = new DateTime(2021, 1, 11, 10, 56, 47, 754, DateTimeKind.Local).AddTicks(7020),
                            EmployeeId = 21,
                            FirstName = "Armando",
                            LastName = "Kuvalis",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 49,
                            DateOfBirth = new DateTime(2009, 11, 20, 4, 58, 38, 825, DateTimeKind.Local).AddTicks(2831),
                            EmployeeId = 21,
                            FirstName = "Ned",
                            LastName = "Weissnat",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 50,
                            DateOfBirth = new DateTime(2015, 9, 5, 20, 41, 16, 217, DateTimeKind.Local).AddTicks(5974),
                            EmployeeId = 22,
                            FirstName = "Lincoln",
                            LastName = "King",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 51,
                            DateOfBirth = new DateTime(2022, 9, 22, 23, 42, 47, 439, DateTimeKind.Local).AddTicks(1067),
                            EmployeeId = 22,
                            FirstName = "Linda",
                            LastName = "Barton",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 52,
                            DateOfBirth = new DateTime(1987, 10, 10, 17, 9, 33, 373, DateTimeKind.Local).AddTicks(8884),
                            EmployeeId = 23,
                            FirstName = "Grant",
                            LastName = "Koss",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 53,
                            DateOfBirth = new DateTime(2017, 3, 25, 4, 42, 17, 908, DateTimeKind.Local).AddTicks(4631),
                            EmployeeId = 24,
                            FirstName = "Leonel",
                            LastName = "Koch",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 54,
                            DateOfBirth = new DateTime(2023, 10, 12, 20, 49, 26, 584, DateTimeKind.Local).AddTicks(524),
                            EmployeeId = 24,
                            FirstName = "Anahi",
                            LastName = "Weissnat",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 55,
                            DateOfBirth = new DateTime(2019, 8, 2, 5, 21, 37, 603, DateTimeKind.Local).AddTicks(9678),
                            EmployeeId = 24,
                            FirstName = "Ila",
                            LastName = "Zulauf",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 56,
                            DateOfBirth = new DateTime(2010, 8, 17, 7, 18, 26, 549, DateTimeKind.Local).AddTicks(8949),
                            EmployeeId = 25,
                            FirstName = "Georgette",
                            LastName = "Kohler",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 57,
                            DateOfBirth = new DateTime(2018, 11, 29, 17, 0, 30, 421, DateTimeKind.Local).AddTicks(1638),
                            EmployeeId = 26,
                            FirstName = "Jeffery",
                            LastName = "Runte",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 58,
                            DateOfBirth = new DateTime(2022, 6, 23, 0, 40, 32, 147, DateTimeKind.Local).AddTicks(4721),
                            EmployeeId = 27,
                            FirstName = "Demond",
                            LastName = "Jacobs",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 59,
                            DateOfBirth = new DateTime(2018, 6, 7, 13, 40, 9, 382, DateTimeKind.Local).AddTicks(8615),
                            EmployeeId = 27,
                            FirstName = "Dorthy",
                            LastName = "Buckridge",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 60,
                            DateOfBirth = new DateTime(2021, 3, 28, 4, 9, 56, 225, DateTimeKind.Local).AddTicks(8834),
                            EmployeeId = 27,
                            FirstName = "Dave",
                            LastName = "Hansen",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 61,
                            DateOfBirth = new DateTime(2006, 8, 9, 4, 30, 25, 959, DateTimeKind.Local).AddTicks(4165),
                            EmployeeId = 27,
                            FirstName = "Richie",
                            LastName = "Hessel",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 62,
                            DateOfBirth = new DateTime(2019, 5, 29, 3, 51, 36, 569, DateTimeKind.Local).AddTicks(2787),
                            EmployeeId = 28,
                            FirstName = "Amanda",
                            LastName = "Feest",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 63,
                            DateOfBirth = new DateTime(1997, 8, 17, 21, 43, 40, 959, DateTimeKind.Local).AddTicks(2571),
                            EmployeeId = 29,
                            FirstName = "Brant",
                            LastName = "Runolfsson",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 64,
                            DateOfBirth = new DateTime(2000, 3, 24, 23, 6, 50, 130, DateTimeKind.Local).AddTicks(6459),
                            EmployeeId = 29,
                            FirstName = "Ayla",
                            LastName = "Hahn",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 65,
                            DateOfBirth = new DateTime(2020, 10, 9, 1, 7, 8, 732, DateTimeKind.Local).AddTicks(4077),
                            EmployeeId = 30,
                            FirstName = "Anya",
                            LastName = "Howell",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 66,
                            DateOfBirth = new DateTime(2017, 10, 13, 15, 48, 16, 601, DateTimeKind.Local).AddTicks(7524),
                            EmployeeId = 30,
                            FirstName = "Adele",
                            LastName = "Hane",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 67,
                            DateOfBirth = new DateTime(2013, 2, 27, 5, 33, 53, 22, DateTimeKind.Local).AddTicks(4643),
                            EmployeeId = 30,
                            FirstName = "Reginald",
                            LastName = "Morissette",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 68,
                            DateOfBirth = new DateTime(2023, 4, 2, 2, 45, 10, 690, DateTimeKind.Local).AddTicks(5068),
                            EmployeeId = 31,
                            FirstName = "Warren",
                            LastName = "Ruecker",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 69,
                            DateOfBirth = new DateTime(2014, 6, 16, 10, 54, 47, 641, DateTimeKind.Local).AddTicks(9716),
                            EmployeeId = 31,
                            FirstName = "Sedrick",
                            LastName = "Witting",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 70,
                            DateOfBirth = new DateTime(2016, 10, 11, 7, 58, 28, 610, DateTimeKind.Local).AddTicks(5116),
                            EmployeeId = 32,
                            FirstName = "Catalina",
                            LastName = "Quigley",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 71,
                            DateOfBirth = new DateTime(2017, 8, 19, 2, 21, 49, 180, DateTimeKind.Local).AddTicks(782),
                            EmployeeId = 32,
                            FirstName = "Ashly",
                            LastName = "Beahan",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 72,
                            DateOfBirth = new DateTime(2019, 3, 18, 17, 31, 15, 941, DateTimeKind.Local).AddTicks(5611),
                            EmployeeId = 33,
                            FirstName = "Wilford",
                            LastName = "Kshlerin",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 73,
                            DateOfBirth = new DateTime(1989, 10, 5, 14, 19, 23, 634, DateTimeKind.Local).AddTicks(5945),
                            EmployeeId = 35,
                            FirstName = "Talia",
                            LastName = "Gulgowski",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 74,
                            DateOfBirth = new DateTime(2007, 7, 10, 4, 20, 19, 334, DateTimeKind.Local).AddTicks(2136),
                            EmployeeId = 35,
                            FirstName = "Ned",
                            LastName = "Nader",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 75,
                            DateOfBirth = new DateTime(2023, 5, 16, 9, 2, 27, 118, DateTimeKind.Local).AddTicks(8630),
                            EmployeeId = 36,
                            FirstName = "Abdul",
                            LastName = "Thompson",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 76,
                            DateOfBirth = new DateTime(2014, 4, 6, 19, 46, 40, 940, DateTimeKind.Local).AddTicks(3968),
                            EmployeeId = 36,
                            FirstName = "June",
                            LastName = "Douglas",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 77,
                            DateOfBirth = new DateTime(2014, 12, 23, 16, 12, 51, 313, DateTimeKind.Local).AddTicks(2707),
                            EmployeeId = 38,
                            FirstName = "Hilbert",
                            LastName = "Mayert",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 78,
                            DateOfBirth = new DateTime(2015, 1, 31, 14, 9, 4, 153, DateTimeKind.Local).AddTicks(4955),
                            EmployeeId = 38,
                            FirstName = "Tobin",
                            LastName = "Cassin",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 79,
                            DateOfBirth = new DateTime(2022, 7, 14, 21, 35, 40, 198, DateTimeKind.Local).AddTicks(629),
                            EmployeeId = 38,
                            FirstName = "Constantin",
                            LastName = "Boyle",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 80,
                            DateOfBirth = new DateTime(2015, 2, 7, 17, 56, 28, 548, DateTimeKind.Local).AddTicks(3460),
                            EmployeeId = 39,
                            FirstName = "Kareem",
                            LastName = "Howell",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 81,
                            DateOfBirth = new DateTime(2023, 10, 29, 9, 22, 43, 998, DateTimeKind.Local).AddTicks(7318),
                            EmployeeId = 39,
                            FirstName = "Kianna",
                            LastName = "Hoeger",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 82,
                            DateOfBirth = new DateTime(2020, 8, 23, 13, 16, 23, 48, DateTimeKind.Local).AddTicks(8684),
                            EmployeeId = 39,
                            FirstName = "Mckayla",
                            LastName = "Roob",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 83,
                            DateOfBirth = new DateTime(1999, 6, 21, 9, 18, 9, 0, DateTimeKind.Local).AddTicks(5910),
                            EmployeeId = 40,
                            FirstName = "Orie",
                            LastName = "Veum",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 84,
                            DateOfBirth = new DateTime(2013, 6, 7, 19, 1, 56, 861, DateTimeKind.Local).AddTicks(1455),
                            EmployeeId = 40,
                            FirstName = "Katrine",
                            LastName = "Paucek",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 85,
                            DateOfBirth = new DateTime(2019, 11, 9, 9, 55, 30, 657, DateTimeKind.Local).AddTicks(2284),
                            EmployeeId = 40,
                            FirstName = "Shea",
                            LastName = "Jacobi",
                            Relationship = 3
                        });
                });

            modelBuilder.Entity("Api.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2012, 5, 3, 11, 40, 41, 994, DateTimeKind.Local).AddTicks(7982),
                            FirstName = "Caesar",
                            LastName = "Herzog",
                            Salary = 148000m
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2023, 5, 13, 2, 9, 11, 339, DateTimeKind.Local).AddTicks(2343),
                            FirstName = "Wilton",
                            LastName = "Harber",
                            Salary = 170000m
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2001, 4, 29, 4, 30, 48, 831, DateTimeKind.Local).AddTicks(9800),
                            FirstName = "Roma",
                            LastName = "Veum",
                            Salary = 136000m
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2014, 7, 2, 1, 28, 11, 236, DateTimeKind.Local).AddTicks(8826),
                            FirstName = "Kasandra",
                            LastName = "Hayes",
                            Salary = 83000m
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2015, 7, 10, 16, 24, 33, 842, DateTimeKind.Local).AddTicks(1102),
                            FirstName = "Granville",
                            LastName = "Ferry",
                            Salary = 92000m
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2016, 12, 28, 7, 42, 38, 279, DateTimeKind.Local).AddTicks(8133),
                            FirstName = "Zelma",
                            LastName = "Jaskolski",
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1978, 12, 20, 10, 7, 17, 412, DateTimeKind.Local).AddTicks(7856),
                            FirstName = "Ressie",
                            LastName = "Nolan",
                            Salary = 124000m
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2018, 9, 27, 3, 0, 9, 326, DateTimeKind.Local).AddTicks(9327),
                            FirstName = "Shyanne",
                            LastName = "McClure",
                            Salary = 186000m
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2009, 2, 2, 10, 10, 53, 145, DateTimeKind.Local).AddTicks(3337),
                            FirstName = "Violette",
                            LastName = "Hoeger",
                            Salary = 145000m
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2021, 6, 21, 18, 34, 11, 50, DateTimeKind.Local).AddTicks(6927),
                            FirstName = "Jacinto",
                            LastName = "Reichel",
                            Salary = 196000m
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1998, 6, 29, 5, 54, 3, 799, DateTimeKind.Local).AddTicks(7353),
                            FirstName = "Micah",
                            LastName = "Nader",
                            Salary = 129000m
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(2018, 3, 28, 22, 19, 13, 716, DateTimeKind.Local).AddTicks(66),
                            FirstName = "Ken",
                            LastName = "Kuhic",
                            Salary = 107000m
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1987, 7, 25, 15, 7, 12, 223, DateTimeKind.Local).AddTicks(227),
                            FirstName = "Jaiden",
                            LastName = "Beer",
                            Salary = 50000m
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1986, 12, 8, 0, 53, 32, 637, DateTimeKind.Local).AddTicks(8366),
                            FirstName = "Arne",
                            LastName = "Champlin",
                            Salary = 152000m
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(2004, 9, 23, 8, 31, 52, 91, DateTimeKind.Local).AddTicks(4267),
                            FirstName = "Lula",
                            LastName = "Kessler",
                            Salary = 104000m
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(1998, 4, 18, 13, 53, 18, 158, DateTimeKind.Local).AddTicks(4810),
                            FirstName = "Aletha",
                            LastName = "Bauch",
                            Salary = 182000m
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(1985, 11, 2, 14, 43, 55, 380, DateTimeKind.Local).AddTicks(4412),
                            FirstName = "Irma",
                            LastName = "Monahan",
                            Salary = 70000m
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(1993, 11, 26, 4, 7, 32, 222, DateTimeKind.Local).AddTicks(2749),
                            FirstName = "Augustus",
                            LastName = "Hodkiewicz",
                            Salary = 99000m
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(1998, 1, 23, 5, 49, 11, 220, DateTimeKind.Local).AddTicks(2784),
                            FirstName = "Jarod",
                            LastName = "Thiel",
                            Salary = 191000m
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(2017, 6, 14, 14, 52, 27, 380, DateTimeKind.Local).AddTicks(1116),
                            FirstName = "Emmy",
                            LastName = "Flatley",
                            Salary = 69000m
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(1990, 1, 16, 10, 45, 34, 611, DateTimeKind.Local).AddTicks(4036),
                            FirstName = "Amalia",
                            LastName = "Cartwright",
                            Salary = 121000m
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(2003, 6, 17, 7, 14, 9, 429, DateTimeKind.Local).AddTicks(4182),
                            FirstName = "Maudie",
                            LastName = "Waelchi",
                            Salary = 71000m
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(2005, 10, 17, 18, 40, 44, 952, DateTimeKind.Local).AddTicks(6206),
                            FirstName = "Katrina",
                            LastName = "Cassin",
                            Salary = 73000m
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(2020, 7, 31, 19, 0, 1, 957, DateTimeKind.Local).AddTicks(9170),
                            FirstName = "Westley",
                            LastName = "Mohr",
                            Salary = 140000m
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(2003, 7, 23, 3, 41, 7, 533, DateTimeKind.Local).AddTicks(9367),
                            FirstName = "Waldo",
                            LastName = "Berge",
                            Salary = 97000m
                        },
                        new
                        {
                            Id = 26,
                            DateOfBirth = new DateTime(2020, 8, 20, 12, 50, 24, 840, DateTimeKind.Local).AddTicks(451),
                            FirstName = "Willow",
                            LastName = "Considine",
                            Salary = 162000m
                        },
                        new
                        {
                            Id = 27,
                            DateOfBirth = new DateTime(2011, 3, 23, 22, 19, 18, 608, DateTimeKind.Local).AddTicks(9955),
                            FirstName = "Kadin",
                            LastName = "Macejkovic",
                            Salary = 189000m
                        },
                        new
                        {
                            Id = 28,
                            DateOfBirth = new DateTime(2001, 2, 7, 21, 46, 19, 284, DateTimeKind.Local).AddTicks(8231),
                            FirstName = "Flavio",
                            LastName = "Connelly",
                            Salary = 159000m
                        },
                        new
                        {
                            Id = 29,
                            DateOfBirth = new DateTime(2014, 2, 2, 1, 39, 16, 229, DateTimeKind.Local).AddTicks(7459),
                            FirstName = "Toni",
                            LastName = "Hackett",
                            Salary = 104000m
                        },
                        new
                        {
                            Id = 30,
                            DateOfBirth = new DateTime(2000, 4, 27, 9, 35, 30, 154, DateTimeKind.Local).AddTicks(9691),
                            FirstName = "Danika",
                            LastName = "Ullrich",
                            Salary = 77000m
                        },
                        new
                        {
                            Id = 31,
                            DateOfBirth = new DateTime(1990, 6, 30, 1, 18, 22, 703, DateTimeKind.Local).AddTicks(8068),
                            FirstName = "Jerome",
                            LastName = "Ernser",
                            Salary = 199000m
                        },
                        new
                        {
                            Id = 32,
                            DateOfBirth = new DateTime(1983, 9, 14, 10, 9, 25, 798, DateTimeKind.Local).AddTicks(205),
                            FirstName = "Gina",
                            LastName = "Kohler",
                            Salary = 151000m
                        },
                        new
                        {
                            Id = 33,
                            DateOfBirth = new DateTime(2014, 12, 28, 10, 28, 12, 902, DateTimeKind.Local).AddTicks(6735),
                            FirstName = "Jude",
                            LastName = "Kuhn",
                            Salary = 102000m
                        },
                        new
                        {
                            Id = 34,
                            DateOfBirth = new DateTime(2014, 2, 3, 16, 49, 31, 710, DateTimeKind.Local).AddTicks(6850),
                            FirstName = "Lily",
                            LastName = "Bode",
                            Salary = 57000m
                        },
                        new
                        {
                            Id = 35,
                            DateOfBirth = new DateTime(2022, 12, 5, 9, 52, 1, 545, DateTimeKind.Local).AddTicks(5298),
                            FirstName = "Quinten",
                            LastName = "Hamill",
                            Salary = 95000m
                        },
                        new
                        {
                            Id = 36,
                            DateOfBirth = new DateTime(2019, 8, 12, 6, 53, 7, 375, DateTimeKind.Local).AddTicks(6917),
                            FirstName = "Lenora",
                            LastName = "Gorczany",
                            Salary = 114000m
                        },
                        new
                        {
                            Id = 37,
                            DateOfBirth = new DateTime(1984, 3, 9, 7, 14, 51, 892, DateTimeKind.Local).AddTicks(7214),
                            FirstName = "Esta",
                            LastName = "Dare",
                            Salary = 138000m
                        },
                        new
                        {
                            Id = 38,
                            DateOfBirth = new DateTime(2021, 5, 2, 6, 18, 9, 990, DateTimeKind.Local).AddTicks(2540),
                            FirstName = "Nash",
                            LastName = "Koch",
                            Salary = 113000m
                        },
                        new
                        {
                            Id = 39,
                            DateOfBirth = new DateTime(1997, 9, 20, 18, 27, 50, 51, DateTimeKind.Local).AddTicks(5667),
                            FirstName = "Norwood",
                            LastName = "Ward",
                            Salary = 103000m
                        },
                        new
                        {
                            Id = 40,
                            DateOfBirth = new DateTime(2016, 3, 26, 23, 12, 17, 639, DateTimeKind.Local).AddTicks(4812),
                            FirstName = "Wilhelm",
                            LastName = "Rutherford",
                            Salary = 67000m
                        });
                });

            modelBuilder.Entity("Api.Models.Dependent", b =>
                {
                    b.HasOne("Api.Models.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Api.Models.Employee", b =>
                {
                    b.Navigation("Dependents");
                });
#pragma warning restore 612, 618
        }
    }
}
